---
- hosts: localhost ## control
  become: true
  remote_user: remoteuser

  tasks:
    - name: create backup directory
      file:
        path: /backup
        state: directory
        mode: 0777

- hosts: all  ## node1, node2, node3
  become: true

  tasks:
    - name: make a /tmp/backup directory
      file:
        path: /tmp/backup
        state: directory
        mode: 0755

    - name: archive to /etc/ directory
      archive:
        path: /etc/
        dest: /tmp/backup/etcbackup.tar.gz
        mode: 0755

    - name: donwload control node for all nodes
      fetch:
        src: /tmp/backup/etcbackup.tar.gz
        dest: /backup/{{ inventory_hostname }}-etcbackup.tar.gz
        flat: true
