---
- hosts: all
  vars:
    ramsize: 1000   ## free -h
  tasks:
    - name: check memory size
      fail:
        msg: Memory is so small
      when: ansible_memtotal_mb < ramsize

    - name: show the memory_total_size
      debug:
        msg: memory enough
      when: ansible_memtotal_mb > ramsize
