---
- hosts: all
  vars:
    ramsize: 1500   ## free -h
  tasks:
    - name: check memory size
      fail:
        msg: This server memory size is lower than {{ ramsize }}
      when: ansible_memtotal_mb < ramsize    ## ansible node3.example.com -m setup | grep -A5 -i ansible_mem
      ignore_errors: true

    - name: check memory size ## 추가 
      shell: free -m | grep Mem | awk '{ print $2}'
      register: memory_total_size

    - name: show the memory_total_size
      debug:
        msg: "{{ memory_total_size }}"

    - name: next step process
      debug:
        msg: "hehehe"

    - name: swappiness set to 50 if ramsize is small
      sysctl:
        name: vm.swappiness
        value: 50
        sysctl_set: true
        reload: true
      when: ansible_memtotal_mb < ramsize
