---
- hosts: all

  tasks:
    - name: create parition on /dev/sdb
      parted:
        device: /dev/sdb
        number: 1
        state: present
        flags: [lvm]
        part_start: 5GiB

    - name: show message if not exist /dev/sdb disk
      debug:
        msg: the /dev/sdb disk is not exist
      failed_when: ansible_devices.sdb is not defined

    - name: create testvg as VG
      lvg:
        vg: testvg
        pvs: /dev/sdb1
        state: present

    - name: create testlv in testvg
      lvol:
        vg: testvg
        lv: testlv
        size: 1G

    - name: show message volume or space is not enough
      fail:
        msg: Not enough disk space
      when: ansible_lvm.vgs.testvg is defined and (( ansible_lvm.vgs.testvg.size_g | float ) < 150.0 )

    - name: create filesystem to testlv
      filesystem:
        fstype: xfs
        dev: /dev/testvg/testlv

    - name: mount testlv to /mnt/testlv
      mount:
        path: /mnt/testlv
        src: /dev/testvg/testlv
        state: mounted
        fstype: xfs
