---
- hosts: localhost
  vars:
    list_one: [사과, 오징어, 잘생김]
    list_two: [apple, squid, what]

  tasks:
    - name: loop with two lists
      debug:
        msg: "{{ item.0 }} - {{ item.1 }}"
      loop:
        - "{{ list_one | zip(list_two) | list }}"
