---
- name: Example with single pool
  hosts: all
  vars:
    timesync_ntp_servers:
      - hostname: ntp.example.com
        pool: true
        iburst: true
  roles:
    - rhel-system-roles.timesync
