---
- name: common
  src: http://repo.example.com/common.tar
- name: httpd
  src: http://repo.example.com/httpd.tar
- name: database
  src: http://repo.example.com/database.tar
- name: service
  src: http://repo.example.com/service.tar
- name: firewalld
  src: http://repo.example.com/firewalld.tar
