---
- hosts: all

  tasks:
    - name: add internal repository
      yum_repository:
        baseurl: http://repo.example.com
        gpgcheck: true
        gpgkey: http://repo.example.com/gpgkey
        name: internal-repo
        description: internal-repo
        enabled: true
