---
- hosts: all
  gather_facts: false
  tasks:
    - name: at scheduler
      at:
        command: touch /tmp/at-scheduler.txt
        count: 1
        units: minutes
        unique: true

    - name: cron scheduler
      cron:
        user: 'remoteuser'
        name: "message hello"
        weekday: '*'
        minute: '*/1'
        hour: '*'
        day: '*'
        month: '*'
        job: 'echo "hello this is cron"'
