- hosts: all

  tasks:
    - name: install base packages
      package:
        name: "{{ item }}"  ## dnf install tmux keepalived screen rear, 장점: 빠름(100), 단점: 중지
        state: present
      loop:                 ## 장점: 어떻게든 설치는 진행. 단점: 느림 (1 x 4)x100 = 400이상
          - tmux            ## dnf install tmux                 
          - keepalived      ## dnf install keepalived
          - screen          ## dnf install screen
          - rear            ## dnf install rear
      ignore_errors: true

    - name: install httpd package
      package:
        name: httpd
        state: present
      notify: start to httpd
      when: "inventory_hostname in groups['webserver']"

    - name: install database package
      package:
        name: mariadb-server
        state: present
      notify: start to mariadb        
      when: "inventory_hostname in groups['database']"
      ignore_errors: true


    - name: install middleware package
      package:
        name: tomcat
        state: present
      notify: start to tomcat
      when: "inventory_hostname in groups['middleware']"    ## inventory_hostname == node3.example.com

  handlers:
    - name: start to httpd
      service:
        name: httpd
        state: started
        enabled: true

    - name: start to mariadb
      service:
        name: mariadb-server
        state: started
        enabled: true

    - name: start to tomcat
      service:
        name: tomcat
        state: started
        enabled: true
