---
- hosts: all

  tasks:
    - name: set X11Forwading to disabled permanently
      lineinfile:       ## ansible-doc lineinfile
        path: /etc/ssh/sshd_config
        regex: "^X11Forwarding"       ## 먼저 있는지 없는지 확인
        line: "X11Forwarding no"      ## 없으면 추가
      notify: restart to sshd service

    - name: install httpd package
      package:
        name: httpd
        state: present      ## latest --> update

    - name: set httpd servername
      lineinfile:
        path: /etc/httpd/conf/httpd.conf    ## grep -i servername /etc/httpd/conf/httpd.conf
        regex: "^ServerName"
        line: "ServerName {{ inventory_hostname }}"
      notify: restart to httpd service

    - name: set max tried authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: "^MaxAuthTries"
        line: "MaxAuthTries 3"
      notify: restart to sshd service

  handlers:
    - name: restart to sshd service
      systemd:
        name: sshd
        state: restarted

    - name: restart to httpd service
      systemd:
        name: httpd
        state: restarted
