---
- hosts: all

  tasks:
    - name: add internal repository
      yum_repository:
        baseurl: http://repo.example.com
        gpgcheck: true
        gpgkey: http://repo.example.com/gpgkey
        name: internal-repo
        description: internal-repo
        enabled: true
        module_hotfixes: true

    - name: install httpd
      package:
        name: httpd
        state: present
      when: "inventory_hostname in groups['webserver']"

    - name: install database
      package:
        name:
          - mariadb-server   ## dnf install mariadb-server mariadb
          - mariadb
        state: present
      when: "inventory_hostname in groups['database']"
      ignore_errors: true

    - name: install tomcat
      package:
        name: tomcat
        state: present
      when: "inventory_hostname in groups['middleware']"

    - name: delete all packages
      package:
        name:
          - tomcat
          - mariadb-server
          - mariabd
          - httpd
        state: absent
